RollingRestrooms/Controllers/TestMenuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RollingRestrooms.Models;

namespace RollingRestrooms.Controllers
{
    public class TestMenuController : Controller
    {
        private UserManagementEntities db = new UserManagementEntities();

        //
        // GET: /TestMenu/

        public ActionResult Index()
        {
            var model = db.aut_menu
                .OrderBy(x => x.menu_id).ThenBy(x => x.menu_no)
                .Where(x => x.menu_no >= 2 && x.menu_no <=4 )
                .ToList();

           // ViewBag.test = "jjjjjjjjjjj";

            return View(model);

            //return View(db.aut_menu.ToList());
        }

        //
        // GET: /TestMenu/Details/5

        public ActionResult Details(string id = null)
        {
            aut_menu aut_menu = db.aut_menu.Find(id);
            if (aut_menu == null)
            {
                return HttpNotFound();
            }
            return View(aut_menu);
        }

        //
        // GET: /TestMenu/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /TestMenu/Create

        [HttpPost]
        public ActionResult Create(aut_menu aut_menu)
        {
            if (ModelState.IsValid)
            {
                db.aut_menu.Add(aut_menu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aut_menu);
        }

        //
        // GET: /TestMenu/Edit/5

        public ActionResult Edit(string id = null)
        {
            aut_menu aut_menu = db.aut_menu.Find(id);
            if (aut_menu == null)
            {
                return HttpNotFound();
            }
            return View(aut_menu);
        }

        //
        // POST: /TestMenu/Edit/5

        [HttpPost]
        public ActionResult Edit(aut_menu aut_menu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aut_menu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aut_menu);
        }

        //
        // GET: /TestMenu/Delete/5

        public ActionResult Delete(string id = null)
        {
            aut_menu aut_menu = db.aut_menu.Find(id);
            if (aut_menu == null)
            {
                return HttpNotFound();
            }
            return View(aut_menu);
        }

        //
        // POST: /TestMenu/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id)
        {
            aut_menu aut_menu = db.aut_menu.Find(id);
            db.aut_menu.Remove(aut_menu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

RollingRestrooms/Views/TestMenu/Create.cshtml
@model RollingRestrooms.Models.aut_menu

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>aut_menu</legend>

       

        <div class="editor-label">
            @Html.LabelFor(model => model.modu_id)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.modu_id)
            @Html.ValidationMessageFor(model => model.modu_id)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.menu_no)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.menu_no)
            @Html.ValidationMessageFor(model => model.menu_no)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.menu_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.menu_name)
            @Html.ValidationMessageFor(model => model.menu_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.menu_filepath)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.menu_filepath)
            @Html.ValidationMessageFor(model => model.menu_filepath)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.menu_status)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.menu_status)
            @Html.ValidationMessageFor(model => model.menu_status)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.menu_canceldate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.menu_canceldate)
            @Html.ValidationMessageFor(model => model.menu_canceldate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.menu_cancellogin)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.menu_cancellogin)
            @Html.ValidationMessageFor(model => model.menu_cancellogin)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.insert_date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.insert_date)
            @Html.ValidationMessageFor(model => model.insert_date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.insert_login)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.insert_login)
            @Html.ValidationMessageFor(model => model.insert_login)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.update_date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.update_date)
            @Html.ValidationMessageFor(model => model.update_date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.update_login)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.update_login)
            @Html.ValidationMessageFor(model => model.update_login)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RollingRestrooms/Views/TestMenu/Delete.cshtml
@model RollingRestrooms.Models.aut_menu

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>aut_menu</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.menu_id)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.menu_id)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.modu_id)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.modu_id)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.menu_no)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.menu_no)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.menu_name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.menu_name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.menu_filepath)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.menu_filepath)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.menu_status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.menu_status)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.menu_canceldate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.menu_canceldate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.menu_cancellogin)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.menu_cancellogin)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.insert_date)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.insert_date)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.insert_login)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.insert_login)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.update_date)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.update_date)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.update_login)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.update_login)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

RollingRestrooms/Views/TestMenu/Details.cshtml
@model RollingRestrooms.Models.aut_menu

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>aut_menu</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.menu_id)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.menu_id)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.modu_id)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.modu_id)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.menu_no)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.menu_no)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.menu_name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.menu_name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.menu_filepath)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.menu_filepath)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.menu_status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.menu_status)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.menu_canceldate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.menu_canceldate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.menu_cancellogin)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.menu_cancellogin)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.insert_date)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.insert_date)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.insert_login)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.insert_login)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.update_date)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.update_date)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.update_login)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.update_login)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RollingRestrooms/Views/TestMenu/Edit.cshtml
@model RollingRestrooms.Models.aut_menu

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>aut_menu</legend>

        <div class="editor-label">
         // @Html.LabelFor(model => model.menu_id) 
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.menu_id)
            @Html.ValidationMessageFor(model => model.menu_id)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.modu_id)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.modu_id)
            @Html.ValidationMessageFor(model => model.modu_id)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.menu_no)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.menu_no)
            @Html.ValidationMessageFor(model => model.menu_no)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.menu_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.menu_name)
            @Html.ValidationMessageFor(model => model.menu_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.menu_filepath)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.menu_filepath)
            @Html.ValidationMessageFor(model => model.menu_filepath)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.menu_status)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.menu_status)
            @Html.ValidationMessageFor(model => model.menu_status)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.menu_canceldate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.menu_canceldate)
            @Html.ValidationMessageFor(model => model.menu_canceldate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.menu_cancellogin)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.menu_cancellogin)
            @Html.ValidationMessageFor(model => model.menu_cancellogin)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.insert_date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.insert_date)
            @Html.ValidationMessageFor(model => model.insert_date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.insert_login)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.insert_login)
            @Html.ValidationMessageFor(model => model.insert_login)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.update_date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.update_date)
            @Html.ValidationMessageFor(model => model.update_date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.update_login)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.update_login)
            @Html.ValidationMessageFor(model => model.update_login)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index","TestMenu" )
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RollingRestrooms/Views/TestMenu/Index.cshtml
@model IEnumerable<RollingRestrooms.Models.aut_menu>

@{
    ViewBag.Title = "Index";
    var test = ViewBag.Test;
}

<h2>Index</h2>
@test 
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.menu_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.modu_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.menu_no)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.menu_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.menu_filepath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.menu_status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.menu_canceldate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.menu_cancellogin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.insert_date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.insert_login)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.update_date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.update_login)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.menu_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.modu_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.menu_no)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.menu_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.menu_filepath)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.menu_status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.menu_canceldate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.menu_cancellogin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.insert_date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.insert_login)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.update_date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.update_login)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.modu_id  }) |
            @Html.ActionLink("Details", "Details", new { id=item.modu_id  }) |
            @Html.ActionLink("Delete", "Delete", new {  id=item.modu_id  })
        </td>
    </tr>
}

</table>